apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  releaseName: wordpress
  install:
    remediation:
      retries: 3
  interval: 60m
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wordpress
