apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wordpress
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress
  filterTags:
    pattern: '^([0-9]+\.[0-9]+\.[0-9]+)-debian-[0-9]+-r[0-9]+$'
    extract: '$1'
  policy:
    semver:
      range: ">=6.0.0"
