apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      chart: wordpress
      version: "20.1.2"
  values:
    mariadb:
      auth:
        rootPassword: "CHANGE_ME"
        database: "wordpress"
    wordpressUsername: "admin"
    wordpressPassword: "CHANGE_ME"
    wordpressEmail: "user@example.com"
    service:
      type: ClusterIP
    image:
      tag: 6.4.3-debian-12-r22 # {"$imagepolicy": "flux-system:wordpress:tag"}  
